# Generated by Django 2.2.5 on 2019-09-29 02:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CONTENT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, '作业'), (1, '说明'), (2, '提醒')], verbose_name='类型')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('content', models.CharField(max_length=1024, verbose_name='发布评论')),
                ('status', models.IntegerField(choices=[(0, '已删除'), (1, '生效中')], default=1, verbose_name='评论状态')),
                ('created_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发布者')),
            ],
        ),
        migrations.CreateModel(
            name='COURSE_PAKAGE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='课程包名称')),
                ('descripe', models.CharField(max_length=256, verbose_name='课程包描述')),
                ('created_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='LABEL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='标签名称')),
                ('status', models.IntegerField(choices=[(0, '已删除'), (1, '生效中')], default=1, verbose_name='标签状态')),
                ('created_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='COURSE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, '未定义'), (1, '科学类')], verbose_name='课程类型')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('classroom', models.CharField(max_length=256, verbose_name='课程地点')),
                ('student_grade', models.CharField(max_length=125, verbose_name='年级')),
                ('descripe', models.CharField(max_length=256, verbose_name='课程描述')),
                ('start_time', models.DateTimeField(auto_now=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(auto_now=True, verbose_name='结束时间')),
                ('created_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CONTENT', verbose_name='评论')),
                ('course_pakage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.COURSE_PAKAGE', verbose_name='课程包')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.LABEL', verbose_name='标签')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发布者')),
            ],
        ),
    ]
