# Generated by Django 2.2.5 on 2019-10-09 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0003_auto_20190930_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='LABEL_COURSE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='课程标签名称')),
                ('status', models.IntegerField(choices=[(0, '已删除'), (1, '生效中')], default=1, verbose_name='状态')),
                ('created_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='LABEL_COURSE_PAKAGE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='课程包标签名称')),
                ('status', models.IntegerField(choices=[(0, '已删除'), (1, '生效中')], default=1, verbose_name='状态')),
                ('created_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='content',
        ),
        migrations.RemoveField(
            model_name='course',
            name='label',
        ),
        migrations.AddField(
            model_name='content',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.COURSE', verbose_name='关联课程'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.IntegerField(choices=[(0, '已删除'), (1, '生效中')], default=1, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='course_pakage',
            name='owner',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发布者'),
        ),
        migrations.AddField(
            model_name='course_pakage',
            name='status',
            field=models.IntegerField(choices=[(0, '已删除'), (1, '生效中')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='content',
            name='content',
            field=models.CharField(max_length=1024, verbose_name='评论内容'),
        ),
        migrations.AlterField(
            model_name='content',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发布者'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_pakage',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='course.COURSE_PAKAGE', verbose_name='课程包'),
        ),
        migrations.AlterField(
            model_name='course',
            name='owner',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发布者'),
        ),
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.IntegerField(choices=[(0, '未定义'), (1, '科学'), (1, '文科'), (1, '理科'), (1, '艺术'), (1, '编程'), (1, '体育')], verbose_name='课程类型'),
        ),
        migrations.DeleteModel(
            name='LABEL',
        ),
        migrations.AddField(
            model_name='label_course_pakage',
            name='course_pakage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.COURSE_PAKAGE', verbose_name='关联课程包'),
        ),
        migrations.AddField(
            model_name='label_course_pakage',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发布者'),
        ),
        migrations.AddField(
            model_name='label_course',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.COURSE', verbose_name='关联课程'),
        ),
        migrations.AddField(
            model_name='label_course',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发布者'),
        ),
    ]
