# Generated by Django 2.2.5 on 2019-09-30 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttable', '0002_auto_20190929_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cellphone',
            field=models.IntegerField(default=1, verbose_name='手机号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='created_time',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='student',
            name='classes',
            field=models.IntegerField(choices=[(1, '一年级'), (2, '二年级'), (3, '三年级'), (4, '四年级'), (5, '五年级'), (6, '六年级')], verbose_name='年级'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grades',
            field=models.IntegerField(choices=[(0, '小学'), (1, '初中'), (2, '高中')], verbose_name='学阶'),
        ),
        migrations.AlterField(
            model_name='student_user',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
