# Generated by Django 2.2.5 on 2019-10-09 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttable', '0006_auto_20191009_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_user',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
