# Generated by Django 2.2.5 on 2019-10-09 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttable', '0007_auto_20191009_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_user',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='cellphone',
            field=models.CharField(max_length=20, verbose_name='手机号'),
        ),
    ]
